from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS "articles" (
            "id"          UUID        NOT NULL PRIMARY KEY,
            "slug"        VARCHAR(200) NOT NULL UNIQUE,
            "title"       VARCHAR(500) NOT NULL,
            "excerpt"     TEXT         NOT NULL DEFAULT '',
            "key_points"  JSONB,
            "content"     TEXT         NOT NULL DEFAULT '',
            "category"    VARCHAR(100) NOT NULL DEFAULT '',
            "image_url"   VARCHAR(500) NOT NULL DEFAULT '',
            "author"      VARCHAR(200) NOT NULL DEFAULT '',
            "source"      VARCHAR(200) NOT NULL DEFAULT '',
            "source_icon" VARCHAR(500),
            "source_url"  VARCHAR(500),
            "is_video"    BOOL         NOT NULL DEFAULT FALSE,
            "video_url"   VARCHAR(500),
            "is_internal" BOOL         NOT NULL DEFAULT FALSE,
            "is_featured" BOOL         NOT NULL DEFAULT FALSE,
            "view_count"  INT          NOT NULL DEFAULT 0,
            "published_at" TIMESTAMPTZ NOT NULL,
            "created_at"  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            "tags"        JSONB        NOT NULL DEFAULT '[]'
        );
        CREATE INDEX IF NOT EXISTS "idx_articles_slug"     ON "articles" ("slug");
        CREATE INDEX IF NOT EXISTS "idx_articles_category" ON "articles" ("category");
        CREATE INDEX IF NOT EXISTS "idx_articles_published" ON "articles" ("published_at" DESC);

        INSERT INTO "articles"
            (id, slug, title, excerpt, key_points, content, category, image_url,
             author, source, source_icon, source_url,
             is_video, is_internal, is_featured, published_at, tags)
        VALUES
        (
            gen_random_uuid(),
            'tinubu-unveils-renewed-hope-agenda',
            'President Tinubu Unveils Renewed Hope Agenda for Economic Growth',
            'The President outlined key economic reforms aimed at boosting Nigeria''s GDP and attracting foreign investment in the coming fiscal year.',
            '["GDP growth target of 4.2% set for fiscal year 2026, backed by IMF projections.", "Foreign direct investment incentives include tax holidays and simplified registration for qualifying companies.", "Agricultural output earmarked for a 40% increase through irrigation and mechanisation funding.", "Fuel subsidy removal enters its final phase, with targeted cash transfers for low-income households."]',
            '<p>President Bola Ahmed Tinubu has unveiled a comprehensive economic plan dubbed the "Renewed Hope Agenda" aimed at accelerating Nigeria''s economic growth and development.</p><p>Speaking at the Presidential Villa in Abuja, the President outlined key reforms that will focus on diversifying the economy away from oil dependency, improving infrastructure, and creating jobs for millions of young Nigerians.</p><p>"Our nation stands at a crossroads, and we must choose the path of progress and prosperity," President Tinubu said during the unveiling ceremony attended by cabinet members, governors, and international diplomats.</p><p>The agenda includes plans to increase agricultural output by 40%, boost manufacturing capacity, and position Nigeria as a technology hub in Africa. The President also announced new incentives for foreign investors, including tax breaks and simplified business registration processes.</p><p>Economic analysts have welcomed the plan, noting that it addresses many of the structural challenges that have hindered Nigeria''s economic development. However, some have cautioned that implementation will be key to achieving the ambitious targets.</p>',
            'Politics',
            'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&h=500&fit=crop',
            'Chioma Okafor',
            'Punch Nigeria',
            'https://www.google.com/s2/favicons?domain=punchng.com&sz=32',
            'https://punchng.com',
            FALSE, FALSE, TRUE,
            '2025-01-15 08:00:00+00',
            '["Politics", "Economy", "Nigeria"]'
        ),
        (
            gen_random_uuid(),
            'super-eagles-qualify-afcon-2025',
            'Super Eagles Secure AFCON 2025 Qualification with Stunning Victory',
            'Nigeria''s national team delivered a masterclass performance to clinch their spot at the Africa Cup of Nations with a convincing win.',
            NULL,
            '<p>The Super Eagles of Nigeria have secured their qualification for the 2025 Africa Cup of Nations with an impressive 3-1 victory.</p><p>Goals from Victor Osimhen, Ademola Lookman, and Samuel Chukwueze sealed the deal for the three-time African champions in a match that showcased the best of Nigerian football.</p>',
            'Sports',
            'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=500&fit=crop',
            'Adebayo Johnson',
            'Vanguard',
            'https://www.google.com/s2/favicons?domain=vanguardngr.com&sz=32',
            'https://vanguardngr.com',
            FALSE, FALSE, TRUE,
            '2025-01-15 05:00:00+00',
            '["Sports", "Football", "AFCON"]'
        ),
        (
            gen_random_uuid(),
            'lagos-tech-startup-raises-50m',
            'Lagos-Based Tech Startup Raises $50M in Series B Funding',
            'The fintech company aims to expand its digital payment solutions across West Africa with the new investment round.',
            NULL,
            '<p>A Lagos-based fintech startup has raised $50 million in a Series B funding round led by international venture capital firms.</p><p>The company, which provides digital payment solutions to over 5 million users across Nigeria, plans to use the funding to expand into other West African markets.</p>',
            'Technology',
            'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=500&fit=crop',
            'Fatima Abdullahi',
            'TechCabal',
            'https://www.google.com/s2/favicons?domain=techcabal.com&sz=32',
            'https://techcabal.com',
            FALSE, FALSE, TRUE,
            '2025-01-14 22:00:00+00',
            '["Technology", "Fintech", "Startups"]'
        ),
        (
            gen_random_uuid(),
            'nollywood-film-breaks-box-office',
            'Nollywood Film Breaks Box Office Records with N1.2 Billion Opening',
            'The latest Nollywood blockbuster has shattered all previous records, becoming the highest-grossing Nigerian film in history.',
            NULL,
            '<p>A new Nollywood production has broken all box office records in Nigeria, grossing over N1.2 billion in its opening weekend.</p><p>The film, directed by acclaimed filmmaker Kunle Afolayan, tells the story of Nigeria''s independence struggle and features an ensemble cast of the country''s finest actors.</p>',
            'Entertainment',
            'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&h=500&fit=crop',
            'Ngozi Eze',
            'Premium Times',
            'https://www.google.com/s2/favicons?domain=premiumtimesng.com&sz=32',
            'https://premiumtimesng.com',
            FALSE, FALSE, TRUE,
            '2025-01-14 10:00:00+00',
            '["Entertainment", "Nollywood", "Film"]'
        ),
        (
            gen_random_uuid(),
            'cbn-new-monetary-policy',
            'CBN Announces New Monetary Policy Framework to Stabilize Naira',
            'The Central Bank of Nigeria has introduced new measures aimed at stabilizing the exchange rate and controlling inflation.',
            NULL,
            '<p>The Central Bank of Nigeria has announced a comprehensive new monetary policy framework designed to stabilize the naira and bring inflation under control.</p><p>The new framework includes stricter controls on foreign exchange, new interest rate targets, and a range of measures to boost confidence in the Nigerian currency.</p>',
            'Business',
            'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&h=500&fit=crop',
            'Ibrahim Musa',
            'Businessday NG',
            'https://www.google.com/s2/favicons?domain=businessday.ng&sz=32',
            'https://businessday.ng',
            FALSE, FALSE, TRUE,
            '2025-01-14 06:00:00+00',
            '["Business", "Economy", "CBN"]'
        ),
        (
            gen_random_uuid(),
            'dangote-refinery-full-capacity',
            'Dangote Refinery Reaches Full Production Capacity, Boosting Local Supply',
            'Africa''s largest oil refinery has achieved a major milestone as it reaches full production capacity, reducing Nigeria''s dependence on imported fuel.',
            NULL,
            '<p>The Dangote Refinery has reached its full production capacity, marking a significant milestone for Nigeria''s energy sector.</p><p>The refinery, located in Lagos, is now processing over 650,000 barrels of crude oil per day, making it the largest oil refinery on the African continent.</p>',
            'Business',
            'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=800&h=500&fit=crop',
            'Emeka Obi',
            'Channels TV',
            'https://www.google.com/s2/favicons?domain=channelstv.com&sz=32',
            'https://channelstv.com',
            FALSE, FALSE, FALSE,
            '2025-01-13 10:00:00+00',
            '["Business", "Energy", "Dangote"]'
        ),
        (
            gen_random_uuid(),
            'nigerian-health-workers-strike',
            'Nigerian Health Workers Call Off Strike After Government Agreement',
            'Healthcare workers have agreed to return to work following successful negotiations with the federal government on improved conditions.',
            NULL,
            '<p>Nigerian health workers have called off their nationwide strike after reaching an agreement with the federal government on improved working conditions and salary adjustments.</p><p>The strike, which lasted for three weeks, had severely disrupted healthcare services across the country.</p>',
            'Health',
            'https://images.unsplash.com/photo-1584982751601-97dcc096659c?w=800&h=500&fit=crop',
            'Aisha Bello',
            'The Guardian NG',
            'https://www.google.com/s2/favicons?domain=guardian.ng&sz=32',
            'https://guardian.ng',
            FALSE, FALSE, FALSE,
            '2025-01-12 14:00:00+00',
            '["Health", "Labour", "Government"]'
        ),
        (
            gen_random_uuid(),
            'asuu-new-education-reforms',
            'ASUU Endorses New Education Reform Package for Nigerian Universities',
            'The Academic Staff Union of Universities has given its backing to a comprehensive reform package aimed at improving tertiary education.',
            NULL,
            '<p>The Academic Staff Union of Universities (ASUU) has endorsed a new education reform package that promises to transform Nigerian universities.</p><p>The package includes increased funding, improved infrastructure, and better remuneration for academic staff.</p>',
            'Education',
            'https://images.unsplash.com/photo-1523050854058-8df90110c476?w=800&h=500&fit=crop',
            'Uche Nwosu',
            'Daily Trust',
            'https://www.google.com/s2/favicons?domain=dailytrust.com&sz=32',
            'https://dailytrust.com',
            FALSE, FALSE, FALSE,
            '2025-01-11 10:00:00+00',
            '["Education", "ASUU", "Universities"]'
        ),
        (
            gen_random_uuid(),
            'lagos-carnival-2025-highlights',
            'Lagos Carnival 2025: A Spectacular Celebration of Nigerian Culture',
            'Thousands gathered in Lagos for the annual carnival, showcasing vibrant costumes, music, and dance from across Nigeria''s diverse ethnic groups.',
            NULL,
            '<p>The 2025 Lagos Carnival has been hailed as the most spectacular edition yet, drawing thousands of participants and spectators from around the world.</p><p>The carnival featured colourful floats, traditional costumes, and performances by some of Nigeria''s top musicians.</p>',
            'Photo News',
            'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&h=500&fit=crop',
            'Kemi Adesanya',
            'Pulse Nigeria',
            'https://www.google.com/s2/favicons?domain=pulse.ng&sz=32',
            'https://pulse.ng',
            FALSE, FALSE, FALSE,
            '2025-01-11 08:00:00+00',
            '["Culture", "Lagos", "Entertainment"]'
        ),
        (
            gen_random_uuid(),
            'abuja-infrastructure-development',
            'Abuja Gets N500 Billion Infrastructure Development Boost',
            'The Federal Capital Territory is set for a massive infrastructure overhaul with new roads, bridges, and public facilities.',
            NULL,
            '<p>The Federal Capital Territory Administration has announced a N500 billion infrastructure development plan that will transform Abuja''s landscape.</p><p>The plan covers construction of new expressways, renovation of public parks, and expansion of the city''s water supply network.</p>',
            'Politics',
            'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&h=500&fit=crop',
            'Mohammed Sani',
            'ThisDay Live',
            'https://www.google.com/s2/favicons?domain=thisdaylive.com&sz=32',
            'https://thisdaylive.com',
            FALSE, FALSE, FALSE,
            '2025-01-10 10:00:00+00',
            '["Politics", "Infrastructure", "Abuja"]'
        ),
        (
            gen_random_uuid(),
            'nigerian-music-grammy-nomination',
            'Nigerian Artist Receives Historic Grammy Nomination for Best Global Album',
            'The globally acclaimed artist makes history as the first Nigerian to receive a nomination in this prestigious category.',
            NULL,
            '<p>A Nigerian music artist has made history by receiving a Grammy nomination in the Best Global Music Album category.</p><p>The nomination is seen as a major milestone for Afrobeats music and Nigerian culture on the global stage.</p>',
            'Entertainment',
            'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=500&fit=crop',
            'Tunde Bakare',
            'Vanguard',
            'https://www.google.com/s2/favicons?domain=vanguardngr.com&sz=32',
            'https://vanguardngr.com',
            FALSE, FALSE, FALSE,
            '2025-01-10 08:00:00+00',
            '["Entertainment", "Music", "Grammy"]'
        ),
        (
            gen_random_uuid(),
            'nigeria-renewable-energy-push',
            'Nigeria Launches Ambitious Renewable Energy Program to Power Rural Areas',
            'A new government initiative aims to bring solar and wind energy to millions of Nigerians living in off-grid communities.',
            NULL,
            '<p>Nigeria has launched an ambitious renewable energy program aimed at bringing clean electricity to millions of citizens in rural areas who currently lack access to the power grid.</p><p>The program, backed by international development partners, will deploy solar panels and mini-grid systems across 5,000 communities.</p>',
            'Technology',
            'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=500&fit=crop',
            'Chidi Okoro',
            'Businessday NG',
            'https://www.google.com/s2/favicons?domain=businessday.ng&sz=32',
            'https://businessday.ng',
            FALSE, FALSE, FALSE,
            '2025-01-09 10:00:00+00',
            '["Technology", "Energy", "Environment"]'
        ),
        (
            gen_random_uuid(),
            'documentary-lagos-megacity',
            'Documentary: Lagos — The Rise of Africa''s Megacity',
            'An in-depth look at how Lagos is transforming into one of the world''s most dynamic urban centers.',
            NULL,
            '',
            'Video',
            'https://images.unsplash.com/photo-1618828665011-0abd973f7bb8?w=800&h=500&fit=crop',
            'PTD Video Team',
            'Prime Times Daily',
            '/ptd_logo_blue.png',
            NULL,
            TRUE, TRUE, FALSE,
            '2025-01-15 07:00:00+00',
            '["Lagos", "Documentary", "Urban"]'
        ),
        (
            gen_random_uuid(),
            'interview-finance-minister',
            'Exclusive Interview: Finance Minister on Nigeria''s Economic Future',
            'The Finance Minister discusses the government''s plans for economic recovery and growth.',
            NULL,
            '',
            'Video',
            'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&h=500&fit=crop',
            'PTD Video Team',
            'Prime Times Daily',
            '/ptd_logo_blue.png',
            NULL,
            TRUE, TRUE, FALSE,
            '2025-01-14 09:00:00+00',
            '["Economy", "Interview", "Government"]'
        ),
        (
            gen_random_uuid(),
            'tech-week-lagos-highlights',
            'Tech Week Lagos 2025: Innovation Highlights',
            'The best innovations and startups showcased at this year''s Tech Week Lagos.',
            NULL,
            '',
            'Video',
            'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=500&fit=crop',
            'PTD Video Team',
            'Prime Times Daily',
            '/ptd_logo_blue.png',
            NULL,
            TRUE, TRUE, FALSE,
            '2025-01-13 09:00:00+00',
            '["Technology", "Innovation", "Lagos"]'
        ),
        (
            gen_random_uuid(),
            'afrobeats-global-stage',
            'Afrobeats Takes the Global Stage: A Musical Revolution',
            'How Nigerian music is conquering the world, one beat at a time.',
            NULL,
            '',
            'Video',
            'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800&h=500&fit=crop',
            'PTD Video Team',
            'Prime Times Daily',
            '/ptd_logo_blue.png',
            NULL,
            TRUE, TRUE, FALSE,
            '2025-01-12 09:00:00+00',
            '["Music", "Afrobeats", "Culture"]'
        ),
        (
            gen_random_uuid(),
            'nigerian-cuisine-world',
            'Nigerian Cuisine Goes Global: Jollof Rice Conquers the World',
            'How Nigerian food is gaining international recognition and acclaim.',
            NULL,
            '',
            'Video',
            'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800&h=500&fit=crop',
            'PTD Video Team',
            'Prime Times Daily',
            '/ptd_logo_blue.png',
            NULL,
            TRUE, TRUE, FALSE,
            '2025-01-11 09:00:00+00',
            '["Food", "Culture", "Nigeria"]'
        );
    """


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        DROP TABLE IF EXISTS "articles";
    """
